FIX: Throw an exception on first startup. SerializationException: On load: NoSuchMethodError: The method '[]' was called on null. Receiver: null Tried calling: []("counter")